//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失。
//     
//     创建时间:2013/7/17 星期三 13:45:33
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Draco.DB.ORM.Common;
using Draco.DB.ORM.Mapping;
using Draco.DB.ORM.Mapping.AttrMapping;
namespace Draco.DB.UnitTest.ORM.DAL
{
    /// <summary>
    /// 映射实体类:User
    /// </summary>
    [TableMapping(TypeName = "USER",TableName ="User", IsTable = true,KeyGenerator="GUID")]
    public partial class USEREntity : AbstractEntity
    {
        
        /// <summary> 
        /// 表名称:User
        /// </summary>
        public static string TableName
        {
            get{ return "User";}
        }
        private String _UID;
        private String _Name;
        private String _Alias;
        private String _Gender;
        private Int32 _Age;
        private DateTime _Birthday;
        private Double _Stature;
        private String _Address;
        private Byte[] _Photo;
        private String _Introduction;
        private Byte _IsLocked;
        private DateTime _CreateDate;


        /// <summary> 
        /// 无参构造
        /// </summary>
        public USEREntity() { }
          
        /// <summary> 
        /// 公有属性:UID,字段名称：UID
        /// </summary>
        [PrimaryKeyMapping(PropertyName="UID",ColumnName="UID",FieldType=FieldType.String,FieldLength=128,Remark="")]
        public String UID
        {
            get { return _UID; }
            set
            {
                _UID = value;
                OnPropertyChanged("UID", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Name,字段名称：Name
        /// </summary>
        [FieldMapping(PropertyName="Name",ColumnName="Name",IsNullable=true,FieldType=FieldType.String,FieldLength=128,DefauleValue="",Remark="")]
        public String Name
        {
            get { return _Name; }
            set
            {
                _Name = value;
                OnPropertyChanged("Name", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Alias,字段名称：Alias
        /// </summary>
        [FieldMapping(PropertyName="Alias",ColumnName="Alias",IsNullable=true,FieldType=FieldType.String,FieldLength=128,DefauleValue="",Remark="")]
        public String Alias
        {
            get { return _Alias; }
            set
            {
                _Alias = value;
                OnPropertyChanged("Alias", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Gender,字段名称：Gender
        /// </summary>
        [FieldMapping(PropertyName="Gender",ColumnName="Gender",IsNullable=true,FieldType=FieldType.String,FieldLength=50,DefauleValue="",Remark="")]
        public String Gender
        {
            get { return _Gender; }
            set
            {
                _Gender = value;
                OnPropertyChanged("Gender", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Age,字段名称：Age
        /// </summary>
        [FieldMapping(PropertyName="Age",ColumnName="Age",IsNullable=true,FieldType=FieldType.Int,FieldLength=10,DefauleValue="",Remark="")]
        public Int32 Age
        {
            get { return _Age; }
            set
            {
                _Age = value;
                OnPropertyChanged("Age", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Birthday,字段名称：Birthday
        /// </summary>
        [FieldMapping(PropertyName="Birthday",ColumnName="Birthday",IsNullable=true,FieldType=FieldType.DateTime,FieldLength=23,DefauleValue="",Remark="")]
        public DateTime Birthday
        {
            get { return _Birthday; }
            set
            {
                _Birthday = value;
                OnPropertyChanged("Birthday", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Stature,字段名称：Stature
        /// </summary>
        [FieldMapping(PropertyName="Stature",ColumnName="Stature",IsNullable=true,FieldType=FieldType.Decimal,FieldLength=53,DefauleValue="",Remark="")]
        public Double Stature
        {
            get { return _Stature; }
            set
            {
                _Stature = value;
                OnPropertyChanged("Stature", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Address,字段名称：Address
        /// </summary>
        [FieldMapping(PropertyName="Address",ColumnName="Address",IsNullable=true,FieldType=FieldType.String,FieldLength=512,DefauleValue="",Remark="")]
        public String Address
        {
            get { return _Address; }
            set
            {
                _Address = value;
                OnPropertyChanged("Address", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Photo,字段名称：Photo
        /// </summary>
        [FieldMapping(PropertyName="Photo",ColumnName="Photo",IsNullable=true,FieldType=FieldType.Binary,FieldLength=2147483647,DefauleValue="",Remark="")]
        public Byte[] Photo
        {
            get { return _Photo; }
            set
            {
                _Photo = value;
                OnPropertyChanged("Photo", value);
            }
        }          
        /// <summary> 
        /// 公有属性:Introduction,字段名称：Introduction
        /// </summary>
        [FieldMapping(PropertyName="Introduction",ColumnName="Introduction",IsNullable=true,FieldType=FieldType.String,FieldLength=2147483647,DefauleValue="",Remark="")]
        public String Introduction
        {
            get { return _Introduction; }
            set
            {
                _Introduction = value;
                OnPropertyChanged("Introduction", value);
            }
        }          
        /// <summary> 
        /// 公有属性:IsLocked,字段名称：IsLocked
        /// </summary>
        [FieldMapping(PropertyName="IsLocked",ColumnName="IsLocked",IsNullable=true,FieldType=FieldType.Bit,FieldLength=1,DefauleValue="",Remark="")]
        public Byte IsLocked
        {
            get { return _IsLocked; }
            set
            {
                _IsLocked = value;
                OnPropertyChanged("IsLocked", value);
            }
        }          
        /// <summary> 
        /// 公有属性:CreateDate,字段名称：CreateDate
        /// </summary>
        [FieldMapping(PropertyName="CreateDate",ColumnName="CreateDate",IsNullable=true,FieldType=FieldType.DateTime,FieldLength=23,DefauleValue="",Remark="")]
        public DateTime CreateDate
        {
            get { return _CreateDate; }
            set
            {
                _CreateDate = value;
                OnPropertyChanged("CreateDate", value);
            }
        }
    }

    /// <summary>
    /// USER的DAO
    /// </summary>
    public partial class DAO4USEREntity : EntityHandler<USEREntity>
    {
        ///<summary>
        ///构造DAO
        ///</summary>
        /// <param name='entity'>实体</param>
        /// <param name='handler'>操作接口</param>
        public DAO4USEREntity(USEREntity entity, Draco.DB.QuickDataBase.IDataBaseHandler handler)
            :base(entity,handler)
        {
        }
    }
}